/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeacherAbsencesRouteImport } from './routes/admin.teacher-absences'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEvaluationsRouteImport } from './routes/admin.evaluations'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminEvaluationsNewRouteImport } from './routes/admin.evaluations.new'
import { Route as AdminEvaluationsIdRouteImport } from './routes/admin.evaluations.$id'
import { Route as AdminEvaluationsIdEditRouteImport } from './routes/admin.evaluations.$id.edit'

const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeacherAbsencesRoute = AdminTeacherAbsencesRouteImport.update({
  id: '/teacher-absences',
  path: '/teacher-absences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationsRoute = AdminEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationsNewRoute = AdminEvaluationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEvaluationsRoute,
} as any)
const AdminEvaluationsIdRoute = AdminEvaluationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEvaluationsRoute,
} as any)
const AdminEvaluationsIdEditRoute = AdminEvaluationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminEvaluationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/evaluations': typeof AdminEvaluationsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-absences': typeof AdminTeacherAbsencesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evaluations/$id': typeof AdminEvaluationsIdRouteWithChildren
  '/admin/evaluations/new': typeof AdminEvaluationsNewRoute
  '/admin/evaluations/$id/edit': typeof AdminEvaluationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/evaluations': typeof AdminEvaluationsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-absences': typeof AdminTeacherAbsencesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/evaluations/$id': typeof AdminEvaluationsIdRouteWithChildren
  '/admin/evaluations/new': typeof AdminEvaluationsNewRoute
  '/admin/evaluations/$id/edit': typeof AdminEvaluationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/evaluations': typeof AdminEvaluationsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-absences': typeof AdminTeacherAbsencesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evaluations/$id': typeof AdminEvaluationsIdRouteWithChildren
  '/admin/evaluations/new': typeof AdminEvaluationsNewRoute
  '/admin/evaluations/$id/edit': typeof AdminEvaluationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/partenaires'
    | '/programmes'
    | '/admin/attendance'
    | '/admin/evaluations'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teacher-absences'
    | '/admin/users'
    | '/admin/'
    | '/admin/evaluations/$id'
    | '/admin/evaluations/new'
    | '/admin/evaluations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/partenaires'
    | '/programmes'
    | '/admin/attendance'
    | '/admin/evaluations'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teacher-absences'
    | '/admin/users'
    | '/admin'
    | '/admin/evaluations/$id'
    | '/admin/evaluations/new'
    | '/admin/evaluations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/partenaires'
    | '/programmes'
    | '/admin/attendance'
    | '/admin/evaluations'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teacher-absences'
    | '/admin/users'
    | '/admin/'
    | '/admin/evaluations/$id'
    | '/admin/evaluations/new'
    | '/admin/evaluations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  PartenairesRoute: typeof PartenairesRoute
  ProgrammesRoute: typeof ProgrammesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teacher-absences': {
      id: '/admin/teacher-absences'
      path: '/teacher-absences'
      fullPath: '/admin/teacher-absences'
      preLoaderRoute: typeof AdminTeacherAbsencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluations': {
      id: '/admin/evaluations'
      path: '/evaluations'
      fullPath: '/admin/evaluations'
      preLoaderRoute: typeof AdminEvaluationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluations/new': {
      id: '/admin/evaluations/new'
      path: '/new'
      fullPath: '/admin/evaluations/new'
      preLoaderRoute: typeof AdminEvaluationsNewRouteImport
      parentRoute: typeof AdminEvaluationsRoute
    }
    '/admin/evaluations/$id': {
      id: '/admin/evaluations/$id'
      path: '/$id'
      fullPath: '/admin/evaluations/$id'
      preLoaderRoute: typeof AdminEvaluationsIdRouteImport
      parentRoute: typeof AdminEvaluationsRoute
    }
    '/admin/evaluations/$id/edit': {
      id: '/admin/evaluations/$id/edit'
      path: '/edit'
      fullPath: '/admin/evaluations/$id/edit'
      preLoaderRoute: typeof AdminEvaluationsIdEditRouteImport
      parentRoute: typeof AdminEvaluationsIdRoute
    }
  }
}

interface AdminEvaluationsIdRouteChildren {
  AdminEvaluationsIdEditRoute: typeof AdminEvaluationsIdEditRoute
}

const AdminEvaluationsIdRouteChildren: AdminEvaluationsIdRouteChildren = {
  AdminEvaluationsIdEditRoute: AdminEvaluationsIdEditRoute,
}

const AdminEvaluationsIdRouteWithChildren =
  AdminEvaluationsIdRoute._addFileChildren(AdminEvaluationsIdRouteChildren)

interface AdminEvaluationsRouteChildren {
  AdminEvaluationsIdRoute: typeof AdminEvaluationsIdRouteWithChildren
  AdminEvaluationsNewRoute: typeof AdminEvaluationsNewRoute
}

const AdminEvaluationsRouteChildren: AdminEvaluationsRouteChildren = {
  AdminEvaluationsIdRoute: AdminEvaluationsIdRouteWithChildren,
  AdminEvaluationsNewRoute: AdminEvaluationsNewRoute,
}

const AdminEvaluationsRouteWithChildren =
  AdminEvaluationsRoute._addFileChildren(AdminEvaluationsRouteChildren)

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminEvaluationsRoute: typeof AdminEvaluationsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeacherAbsencesRoute: typeof AdminTeacherAbsencesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminEvaluationsRoute: AdminEvaluationsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeacherAbsencesRoute: AdminTeacherAbsencesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  PartenairesRoute: PartenairesRoute,
  ProgrammesRoute: ProgrammesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
